### ISSUE TITLE
Problem with entire objects

### ISSUE THREAD

**Issue by valkish** [marciodrosa/FanPlugin#3] opened 2016-04-15 20:55 UTC
Hi marciodrosa,

I love the idea behind your FanPlugin, and even though it does work on smaller areas, then it seems to have problems when it comes to entire objects.

You can see the outcome of a simple arrow object I made (shown in wireframe view). I moved all the faces along normals using FanPlugin v. 1.3. While it was perfectly symmetrical before (top row of image), it now has a wonky asymmetrical appearance (bottom row of image).

![fanpluginv1 3](https://cloud.githubusercontent.com/assets/18489866/14574127/da3cbf94-0359-11e6-8ef9-2a705c89c00d.png)
Is it possible to fix this issue in the plugin? because that would really make this plugin awesome :-)

Thank you in advance for your help.

**Comment by marciodrosa** [comment] 2016-04-16 15:25
Hi valkish, thank you for your feedback. I was able to reproduce the issue, I will take a look. Meanwhile, have you tried to use the Shrink/Fatten feature? Since it now has a "Even Thickness" option (press S or Alt), it is not much different from FAN now.

**Comment by valkish** [comment] 2016-04-18 04:25
Hello again marciodrosa and thank you for the quick reply.

Yes I have tried the Shrink Flatten feature and Solidify Modifier and I have even looked for alternative programs to do this, but unfortunately none of the options I found were able to handle the operation on the simple arrow object without rotating the faces.

So I hope you can make it work with your FAN addon.

**Comment by marciodrosa** [comment] 2016-05-25 12:47
Fixed on version 1.4.

**Closed by marciodrosa** 2016-05-25 12:47 UTC
